name: 'integration tests'
on:
  push:
jobs:
  integration-tests:
    name: java-${{ matrix.java }} integration tests
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    strategy:
      matrix:
        java: [17, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.docker
          key: ${{ runner.os }}-build-${{ hashFiles('**/*gradle*', '**/pom.xml', '**/package.json', '**/package-lock.json') }}
      - run: sudo apt install -yq httpie jq
      - run: command -v docker >/dev/null 2>&1 || { echo >&2 "Docker is required but not installed.  Aborting."; exit 1; }
      - run: command -v http >/dev/null 2>&1 || { echo >&2 "HTTPie is required but not installed.  Aborting."; exit 1; }
      - run: command -v jq >/dev/null 2>&1 || { echo >&2 "jq is required but not installed.  Aborting."; exit 1; }
      - run: cd $GITHUB_WORKSPACE ; ./mvnw clean ; ./mvnw -DskipTests
      - run: cd $GITHUB_WORKSPACE ; ./mvnw spring-boot:start
      - run: |
          cd $GITHUB_WORKSPACE ;
          echo "input-dir:" ;
          ls -lah target/input-dir/ ;
          echo "output-dir:" ;
          ls -lah target/output-dir/ ;
          echo 'message 123' > target/input-dir/123.txt ;
          echo "input-dir:" ;
          ls -lah target/input-dir/ ;
          echo "output-dir:" ;
          ls -lah target/output-dir/ ;
          sleep 2 ;
          echo "input-dir:" ;
          ls -lah target/input-dir/ ;
          echo "output-dir:" ;
          ls -lah target/output-dir/ ;
      - run: cd $GITHUB_WORKSPACE ; ./mvnw spring-boot:stop
